const SESSION_CONFIG={userKey:'currentUsername',sessionKey:'sessionToken',redirectKey:'intendedDestination',lastPageKey:'lastVisitedPage',loginPath:'index.html',defaultDashboard:'dashboard.html'};const SessionManager={isLoggedIn(){const username=sessionStorage.getItem(SESSION_CONFIG.userKey)||localStorage.getItem(SESSION_CONFIG.userKey);const sessionToken=sessionStorage.getItem(SESSION_CONFIG.sessionKey)||localStorage.getItem(SESSION_CONFIG.sessionKey);return!!(username&&username!=='Guest')},getCurrentUser(){return{username:sessionStorage.getItem(SESSION_CONFIG.userKey)||localStorage.getItem(SESSION_CONFIG.userKey),sessionToken:sessionStorage.getItem(SESSION_CONFIG.sessionKey)||localStorage.getItem(SESSION_CONFIG.sessionKey)}},setUserSession(username,sessionToken=null){sessionStorage.setItem(SESSION_CONFIG.userKey,username);localStorage.setItem(SESSION_CONFIG.userKey,username);if(sessionToken){sessionStorage.setItem(SESSION_CONFIG.sessionKey,sessionToken);localStorage.setItem(SESSION_CONFIG.sessionKey,sessionToken)}
console.log('✅ User session stored (persistent):',username)},setLastVisitedPage(page=null){const currentPath=page||window.location.pathname;const currentPage=currentPath.split('/').pop()||'index.html';const protectedPages=['dashboard.html','feedbacks.html','my-feedbacks.html','post-feedback.html','post-anonymous.html'];if(protectedPages.includes(currentPage)){sessionStorage.setItem(SESSION_CONFIG.lastPageKey,currentPage);localStorage.setItem(SESSION_CONFIG.lastPageKey,currentPage);console.log('📍 Last visited page stored (persistent):',currentPage)}},getLastVisitedPage(){return sessionStorage.getItem(SESSION_CONFIG.lastPageKey)||localStorage.getItem(SESSION_CONFIG.lastPageKey)},clearLastVisitedPage(){sessionStorage.removeItem(SESSION_CONFIG.lastPageKey);localStorage.removeItem(SESSION_CONFIG.lastPageKey)},clearSession(){sessionStorage.removeItem(SESSION_CONFIG.userKey);localStorage.removeItem(SESSION_CONFIG.userKey);sessionStorage.removeItem(SESSION_CONFIG.sessionKey);localStorage.removeItem(SESSION_CONFIG.sessionKey);sessionStorage.removeItem(SESSION_CONFIG.redirectKey);sessionStorage.removeItem(SESSION_CONFIG.lastPageKey);localStorage.removeItem(SESSION_CONFIG.lastPageKey);sessionStorage.removeItem('loginRedirect');localStorage.removeItem('loginRedirect');localStorage.removeItem('feedbackCooldownEnd');console.log('🚪 User session cleared')},setIntendedDestination(path=null){const destination=path||window.location.pathname+window.location.search;sessionStorage.setItem(SESSION_CONFIG.redirectKey,destination);console.log('📍 Intended destination stored:',destination)},getAndClearIntendedDestination(){const destination=sessionStorage.getItem(SESSION_CONFIG.redirectKey);sessionStorage.removeItem(SESSION_CONFIG.redirectKey);return destination},redirectToLogin(){this.setIntendedDestination();console.log('🔒 Redirecting to login...');window.location.href=SESSION_CONFIG.loginPath},redirectAfterLogin(){const intendedDestination=this.getAndClearIntendedDestination();let redirectPath=SESSION_CONFIG.defaultDashboard;if(intendedDestination&&intendedDestination!=='/'&&intendedDestination!=='/index.html'){redirectPath=intendedDestination.startsWith('/')?intendedDestination.substring(1):intendedDestination}else{sessionStorage.setItem('loginRedirect','true')}
console.log('🎯 Redirecting after login to:',redirectPath);window.location.href=redirectPath},requiresAuth(){const currentPath=window.location.pathname;const currentPage=currentPath.split('/').pop()||'index.html';const isRootPath=currentPath==='/'||currentPath.endsWith('/KV/')||currentPath==='';const publicPages=['index.html','about.html',''];if(isRootPath){return!1}
return!publicPages.includes(currentPage)},initializePageAuth(){const requiresAuth=this.requiresAuth();const isLoggedIn=this.isLoggedIn();const currentPath=window.location.pathname;const currentPage=currentPath.split('/').pop()||'index.html';const isRootPath=currentPath==='/'||currentPath.endsWith('/KV/')||currentPath==='';console.log('🔐 Page auth check:',{currentPath,currentPage,isRootPath,requiresAuth,isLoggedIn});if(requiresAuth&&!isLoggedIn){console.log('⚠️ Authentication required - redirecting to login');this.redirectToLogin();return!1}
if(isLoggedIn&&(isRootPath||currentPage==='index.html')){const lastVisitedPage=this.getLastVisitedPage();const hasIntendedDestination=sessionStorage.getItem(SESSION_CONFIG.redirectKey);if(hasIntendedDestination){const cameFromLogin=sessionStorage.getItem('loginRedirect')==='true';if(cameFromLogin){console.log('✅ Login completed with intended destination - will redirect after login');sessionStorage.removeItem('loginRedirect')}}else if(lastVisitedPage&&lastVisitedPage!=='dashboard.html'){console.log('🔄 Returning user - redirecting to last visited page:',lastVisitedPage);window.location.href=lastVisitedPage;return!1}else{const cameFromLogin=sessionStorage.getItem('loginRedirect')==='true';if(cameFromLogin){console.log('✅ Fresh login completed - redirecting to dashboard');sessionStorage.removeItem('loginRedirect');window.location.href=SESSION_CONFIG.defaultDashboard;return!1}else{console.log('🏠 User accessing root page directly - allowing access')}}}
if(isLoggedIn&&requiresAuth){this.setLastVisitedPage()}
return!0},async validateSession(){const user=this.getCurrentUser();if(!user.username||!user.sessionToken){return!1}
try{if(window.DatabaseHelper&&window.DatabaseHelper.validateSession){const result=await window.DatabaseHelper.validateSession(user.sessionToken);if(!result.valid){console.log('❌ Session validation failed - clearing session');this.clearSession();return!1}
console.log('✅ Session validated successfully');return!0}
return!0}catch(error){console.error('❌ Session validation error:',error);return!1}}};document.addEventListener('DOMContentLoaded',function(){console.log('🔄 Initializing session management...');const persistedUser=localStorage.getItem(SESSION_CONFIG.userKey);const persistedToken=localStorage.getItem(SESSION_CONFIG.sessionKey);const persistedLastPage=localStorage.getItem(SESSION_CONFIG.lastPageKey);if(persistedUser&&!sessionStorage.getItem(SESSION_CONFIG.userKey)){sessionStorage.setItem(SESSION_CONFIG.userKey,persistedUser)}
if(persistedToken&&!sessionStorage.getItem(SESSION_CONFIG.sessionKey)){sessionStorage.setItem(SESSION_CONFIG.sessionKey,persistedToken)}
if(persistedLastPage&&!sessionStorage.getItem(SESSION_CONFIG.lastPageKey)){sessionStorage.setItem(SESSION_CONFIG.lastPageKey,persistedLastPage)}
document.addEventListener('contextmenu',function(e){e.preventDefault()});document.addEventListener('keydown',function(e){if(e.keyCode===123){e.preventDefault()}
if(e.ctrlKey&&e.shiftKey&&['I','J','C'].includes(e.key.toUpperCase())){e.preventDefault()}
if(e.ctrlKey&&e.key.toUpperCase()==='U'){e.preventDefault()}});setTimeout(()=>{SessionManager.initializePageAuth()},100)});window.addEventListener('beforeunload',function(){if(SessionManager.isLoggedIn()){SessionManager.setLastVisitedPage()}});window.addEventListener('pagehide',function(){if(SessionManager.isLoggedIn()){SessionManager.setLastVisitedPage()}});window.SessionManager=SessionManager;window.SESSION_CONFIG=SESSION_CONFIG;console.log('📦 Session management loaded')
