const SUPABASE_CONFIG={url:'https://oymthdbwemelojniclig.supabase.co',apiKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95bXRoZGJ3ZW1lbG9qbmljbGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjk3MjgsImV4cCI6MjA3MjY0NTcyOH0.Tl-vW4L1uDAxPmmfmTP4zkrSyjpJio4Mjt0hxgyXlHI',};let supabase=null;function initializeSupabase(){if(supabase===null&&window.supabase){console.log('🚀 Initializing Supabase connection...');try{supabase=window.supabase.createClient(SUPABASE_CONFIG.url,SUPABASE_CONFIG.apiKey);supabase.auth.onAuthStateChange((event,session)=>{console.log('🔐 Auth state changed:',event);if(session){console.log('👤 User authenticated with Supabase:',session.user.id)}else{console.log('🚪 User logged out from Supabase')}});console.log('✅ Supabase client initialized successfully');console.log('🔗 Supabase URL:',SUPABASE_CONFIG.url);return!0}catch(error){console.error('❌ Failed to initialize Supabase:',error);return!1}}
return supabase!==null}
const DatabaseHelper={async testConnection(){try{if(!supabase){console.error('❌ Supabase client not initialized');return!1}
const{data,error}=await supabase.from('users').select('id').limit(1);if(error){console.error('❌ Database connection failed:',error.message);return!1}
console.log('✅ Database connection successful');return!0}catch(error){console.error('❌ Database connection error:',error);return!1}},async hashPassword(password){try{const encoder=new TextEncoder();const data=encoder.encode(password+'KV_SALT_2024');const hashBuffer=await crypto.subtle.digest('SHA-256',data);const hashArray=Array.from(new Uint8Array(hashBuffer));const hashHex=hashArray.map(byte=>byte.toString(16).padStart(2,'0')).join('');return hashHex}catch(error){console.error('❌ Password hashing failed:',error);throw new Error('Password hashing failed')}},async createUser(userData){try{console.log('📝 Creating new user account...');const hashedPassword=await this.hashPassword(userData.password);const{data:existingUser,error:checkError}=await supabase.from('users').select('username').eq('username',userData.username).maybeSingle();if(existingUser&&!checkError){throw new Error('Username already exists')}
const{data,error}=await supabase.from('users').insert([{username:userData.username,password_hash:hashedPassword,full_name:userData.full_name||userData.username,user_type:userData.user_type||'student',class_section:userData.class_section||null,roll_number:userData.roll_number||null}]).select().single();if(error){console.error('❌ User creation failed:',error);throw new Error(`Failed to create account: ${error.message}`)}
console.log('✅ User account created successfully:',data.username);return{success:!0,user:{id:data.id,username:data.username,user_type:data.user_type,created_at:data.created_at},message:'Account created successfully!'}}catch(error){console.error('❌ Create user error:',error);return{success:!1,error:error.message||'Failed to create account'}}},async authenticateUser(username,password){try{console.log('🔐 Authenticating user login...');const hashedPassword=await this.hashPassword(password);const{data:user,error}=await supabase.from('users').select('id, username, user_type, full_name, is_active, last_login').eq('username',username).eq('password_hash',hashedPassword).eq('is_active',!0).single();if(error||!user){console.log('❌ Login failed: Invalid credentials');return{success:!1,error:'Invalid username or password'}}
await supabase.from('users').update({last_login:new Date().toISOString()}).eq('id',user.id);console.log('✅ User authenticated successfully:',user.username);return{success:!0,user:{id:user.id,username:user.username,user_type:user.user_type,full_name:user.full_name},message:`Welcome back, ${user.username}!`}}catch(error){console.error('❌ Authentication error:',error);return{success:!1,error:'Login failed. Please try again.'}}},async createSession(userId){try{console.log('🔑 Creating user session...');const sessionToken=crypto.randomUUID();const{data,error}=await supabase.rpc('create_user_session',{p_user_id:userId,p_session_token:sessionToken,p_user_agent:navigator.userAgent,p_ip_address:null,p_expires_hours:24});if(error){console.error('❌ Session creation failed:',error);return null}
console.log('✅ Session created successfully');return sessionToken}catch(error){console.error('❌ Session creation error:',error);return null}},async validateSession(sessionToken){try{console.log('🔍 Validating session...');const{data,error}=await supabase.rpc('validate_session_and_get_user',{p_session_token:sessionToken});if(error||!data||data.length===0){console.log('❌ Session validation failed or no data');return{valid:!1}}
const session=data[0];if(!session.is_valid){console.log('❌ Session is invalid or expired');return{valid:!1,reason:'invalid'}}
console.log('✅ Session validated successfully for user:',session.username);return{valid:!0,user:{id:session.user_id,username:session.username,user_type:session.user_type,full_name:session.full_name},expires_at:session.expires_at,time_remaining:session.time_remaining}}catch(error){console.error('❌ Session validation error:',error);return{valid:!1}}},async logout(sessionToken){try{console.log('🚪 Logging out user...');if(sessionToken){const{data,error}=await supabase.rpc('invalidate_session',{p_session_token:sessionToken});if(error){console.error('❌ Session invalidation failed:',error)}}
console.log('✅ User logged out successfully');return!0}catch(error){console.error('❌ Logout error:',error);return!1}},async submitFeedback(feedbackData){try{console.log('📝 Submitting feedback...');const{data,error}=await supabase.from('feedback_submissions').insert([{username:feedbackData.username,feedback_text:feedbackData.text,is_anonymous:feedbackData.isAnonymous,character_count:feedbackData.text.length}]).select().single();if(error){console.error('❌ Feedback submission failed:',error);return{success:!1,error:error.message}}
console.log('✅ Feedback submitted successfully');return{success:!0,data:data,message:'Feedback posted successfully!'}}catch(error){console.error('❌ Feedback submission error:',error);return{success:!1,error:'Failed to submit feedback'}}},async getTodaysFeedbacks(){try{console.log('📚 Fetching today\'s feedbacks...');const today=new Date().toISOString().split('T')[0];console.log('📅 Fetching feedbacks for date:',today);const{data,error}=await supabase.from('feedback_submissions').select('*').eq('submission_date',today).order('created_at',{ascending:!1});if(error){console.error('❌ Failed to fetch feedbacks:',error);return{success:!1,error:error.message,feedbacks:[]}}
console.log(`✅ Fetched ${data ? data.length : 0} feedbacks`);if(!data||data.length===0){console.log('📋 No feedbacks for today, fetching all recent feedbacks...');const{data:allData,error:allError}=await supabase.from('feedback_submissions').select('*').order('created_at',{ascending:!1}).limit(20);if(allError){console.error('❌ Failed to fetch all feedbacks:',allError);return{success:!1,error:allError.message,feedbacks:[]}}
console.log(`✅ Fetched ${allData ? allData.length : 0} recent feedbacks`);return{success:!0,feedbacks:allData||[]}}
return{success:!0,feedbacks:data}}catch(error){console.error('❌ Error fetching feedbacks:',error);return{success:!1,error:'Failed to load feedbacks',feedbacks:[]}}},async getAllFeedbacksWithComments(){try{console.log('📚 Fetching all feedbacks with comment counts...');const{data,error}=await supabase.from('feedback_submissions').select(`
                    *,
                    comment_count:feedback_comments(count)
                `).order('created_at',{ascending:!1}).limit(50);if(error){console.error('❌ Failed to fetch feedbacks with comments:',error);return{success:!1,error:error.message,feedbacks:[]}}
const processedFeedbacks=data?.map(feedback=>({...feedback,comment_count:feedback.comment_count?.[0]?.count||0}))||[];console.log(`✅ Fetched ${processedFeedbacks.length} feedbacks with comment counts`);return{success:!0,feedbacks:processedFeedbacks}}catch(error){console.error('❌ Error fetching feedbacks with comments:',error);return{success:!1,error:'Failed to load feedbacks',feedbacks:[]}}},async getUserFeedbacks(username){try{console.log(`📚 Fetching feedbacks for user: ${username}`);const{data,error}=await supabase.from('feedback_submissions').select('*').eq('username',username).order('created_at',{ascending:!1});if(error){console.error('❌ Failed to fetch user feedbacks:',error);return{success:!1,error:error.message,feedbacks:[]}}
console.log(`✅ Fetched ${data ? data.length : 0} feedbacks for user ${username}`);return{success:!0,feedbacks:data||[]}}catch(error){console.error('❌ Error fetching user feedbacks:',error);return{success:!1,error:'Failed to load user feedbacks',feedbacks:[]}}},async reportFeedback(feedbackId){try{console.log('🚩 Reporting feedback...');const{data:feedback,error:fetchError}=await supabase.from('feedback_submissions').select('report_count').eq('id',feedbackId).single();if(fetchError){throw fetchError}
const newReportCount=(feedback.report_count||0)+1;const{error:updateError}=await supabase.from('feedback_submissions').update({report_count:newReportCount,is_reported:!0}).eq('id',feedbackId);if(updateError){throw updateError}
console.log('✅ Feedback reported successfully');return{success:!0}}catch(error){console.error('❌ Error reporting feedback:',error);return{success:!1,error:error.message}}},async submitComplaint(complaintText){try{console.log('📝 Submitting anonymous complaint...');if(!supabase){console.error('❌ Supabase client not initialized');return{success:!1,error:'Database not ready'}}
const{data,error}=await supabase.from('anonymous_complaints').insert([{complaint_text:complaintText}]);if(error){console.error('❌ Complaint submission failed:',error);return{success:!1,error:error.message}}
console.log('✅ Complaint submitted successfully');return{success:!0,data,message:'Complaint submitted anonymously!'}}catch(error){console.error('❌ Complaint submission error:',error);return{success:!1,error:'Failed to submit complaint'}}},async submitComment(commentData){try{console.log('💬 Submitting comment...');if(!supabase){console.error('❌ Supabase client not initialized');return{success:!1,error:'Database not ready'}}
const{data,error}=await supabase.from('feedback_comments').insert([{feedback_id:commentData.feedbackId,username:commentData.username,comment_text:commentData.text,is_anonymous:commentData.isAnonymous,character_count:commentData.text.length}]).select().single();if(error){console.error('❌ Comment submission failed:',error);return{success:!1,error:error.message}}
console.log('✅ Comment submitted successfully');return{success:!0,data:data,message:'Comment posted successfully!'}}catch(error){console.error('❌ Comment submission error:',error);return{success:!1,error:'Failed to submit comment'}}},async getCommentsForFeedback(feedbackId){try{console.log(`💬 Fetching comments for feedback: ${feedbackId}`);if(!supabase){console.error('❌ Supabase client not initialized');return{success:!1,error:'Database not ready',comments:[]}}
const{data,error}=await supabase.from('feedback_comments').select('*').eq('feedback_id',feedbackId).eq('is_approved',!0).order('created_at',{ascending:!0});if(error){console.error('❌ Failed to fetch comments:',error);return{success:!1,error:error.message,comments:[]}}
console.log(`✅ Fetched ${data ? data.length : 0} comments`);return{success:!0,comments:data||[]}}catch(error){console.error('❌ Error fetching comments:',error);return{success:!1,error:'Failed to load comments',comments:[]}}},async getCommentCount(feedbackId){try{const{count,error}=await supabase.from('feedback_comments').select('*',{count:'exact',head:!0}).eq('feedback_id',feedbackId).eq('is_approved',!0);if(error){console.error('❌ Failed to get comment count:',error);return 0}
return count||0}catch(error){console.error('❌ Error getting comment count:',error);return 0}},async reportComment(commentId){try{console.log('🚩 Reporting comment...');const{data:comment,error:fetchError}=await supabase.from('feedback_comments').select('report_count').eq('id',commentId).single();if(fetchError){throw fetchError}
const newReportCount=(comment.report_count||0)+1;const{error:updateError}=await supabase.from('feedback_comments').update({report_count:newReportCount,is_reported:!0}).eq('id',commentId);if(updateError){throw updateError}
console.log('✅ Comment reported successfully');return{success:!0,message:'Comment reported successfully'}}catch(error){console.error('❌ Error reporting comment:',error);return{success:!1,error:error.message}}},async getUserComments(username){try{console.log(`💬 Fetching comments for user: ${username}`);const{data,error}=await supabase.from('feedback_comments').select(`
                    *,
                    feedback_submissions:feedback_id (
                        id,
                        feedback_text,
                        username,
                        created_at
                    )
                `).eq('username',username).order('created_at',{ascending:!1});if(error){console.error('❌ Failed to fetch user comments:',error);return{success:!1,error:error.message,comments:[]}}
console.log(`✅ Fetched ${data ? data.length : 0} comments for user ${username}`);return{success:!0,comments:data||[]}}catch(error){console.error('❌ Error fetching user comments:',error);return{success:!1,error:'Failed to load user comments',comments:[]}}},async deleteComment(commentId,username){try{console.log('🗑️ Deleting comment...');const{data:comment,error:fetchError}=await supabase.from('feedback_comments').select('username, comment_text').eq('id',commentId).single();if(fetchError){console.error('❌ Error fetching comment for deletion:',fetchError);return{success:!1,error:'Comment not found'}}
if(comment.username!==username){console.error('❌ User does not own this comment');return{success:!1,error:'You can only delete your own comments'}}
const{error}=await supabase.from('feedback_comments').delete().eq('id',commentId);if(error){console.error('❌ Error deleting comment:',error);return{success:!1,error:error.message}}
console.log('✅ Comment deleted successfully');return{success:!0,message:'Comment deleted successfully'}}catch(error){console.error('❌ Error deleting comment:',error);return{success:!1,error:error.message}}},async sendMessage(messageData){try{console.log('💬 Sending private message...');if(!supabase){console.error('❌ Supabase client not initialized');return{success:!1,error:'Database not ready'}}
const currentUser=SessionManager.getCurrentUser();if(!currentUser||!currentUser.username){return{success:!1,error:'User not authenticated. Please log in again.'}}
const{data:user,error:userError}=await supabase.from('users').select('id').eq('username',currentUser.username).single();if(userError||!user){console.error('❌ Error fetching current user:',userError);return{success:!1,error:'Unable to verify user identity.'}}
if(messageData.senderId!==user.id){console.error('❌ Sender ID does not match current user ID');return{success:!1,error:'Invalid sender. You can only send messages as yourself.'}}
console.log('📝 Message data:',messageData);const{data,error}=await supabase.from('messages').insert([{sender_id:messageData.senderId,receiver_id:messageData.receiverId,content:messageData.content}]).select().single();if(error){console.error('❌ Message sending failed:',error);let errorMessage=error.message;if(error.code==='42501'){errorMessage='Permission denied. You may not have permission to send messages.'}else if(error.code==='23503'){errorMessage='Invalid user ID. The sender or receiver may not exist.'}
return{success:!1,error:errorMessage}}
console.log('✅ Message sent successfully');return{success:!0,data:data,message:'Message sent successfully!'}}catch(error){console.error('❌ Message sending error:',error);return{success:!1,error:'Failed to send message: '+error.message}}},async getMessagesBetweenUsers(userId1,userId2){try{console.log(`💬 Fetching messages between users: ${userId1} and ${userId2}`);if(!supabase){console.error('❌ Supabase client not initialized');return{success:!1,error:'Database not ready',messages:[]}}
const{data,error}=await supabase.from('messages').select('*').or(`and(sender_id.eq.${userId1},receiver_id.eq.${userId2}),and(sender_id.eq.${userId2},receiver_id.eq.${userId1})`).order('created_at',{ascending:!0});if(error){console.error('❌ Failed to fetch messages:',error);return{success:!1,error:error.message,messages:[]}}
console.log(`✅ Fetched ${data ? data.length : 0} messages`);return{success:!0,messages:data||[]}}catch(error){console.error('❌ Error fetching messages:',error);return{success:!1,error:'Failed to load messages: '+error.message,messages:[]}}},subscribeToMessages(userId1,userId2,callback){try{console.log(`📡 Subscribing to messages between users: ${userId1} and ${userId2}`);if(!supabase){console.error('❌ Supabase client not initialized');return null}
const channelName=`messages-${userId1}-${userId2}`;console.log(`📡 Creating channel: ${channelName}`);const channel=supabase.channel(channelName).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},(payload)=>{console.log('📥 New message payload received:',payload);const message=payload.new;console.log('📥 Checking message relevance:',{messageSenderId:message.sender_id,messageReceiverId:message.receiver_id,userId1:userId1,userId2:userId2});if((message.sender_id===userId1&&message.receiver_id===userId2)||(message.sender_id===userId2&&message.receiver_id===userId1)){console.log('📥 Message is relevant, calling callback');callback(message)}else{console.log('📥 Message is not relevant to current conversation, ignoring')}}).subscribe((status,err)=>{console.log('📡 Subscription status update:',{status,err});if(status==='SUBSCRIBED'){console.log('✅ Successfully subscribed to messages')}else if(status==='CHANNEL_ERROR'){console.error('❌ Channel error in message subscription:',err)}else if(status==='CLOSED'){console.log('🔒 Message subscription channel closed')}});console.log('✅ Subscribed to messages');return channel}catch(error){console.error('❌ Error subscribing to messages:',error);return null}},unsubscribeFromMessages(channel){try{if(channel){supabase.removeChannel(channel);console.log('✅ Unsubscribed from messages')}}catch(error){console.error('❌ Error unsubscribing from messages:',error)}}};window.DatabaseHelper=DatabaseHelper;window.SUPABASE_CONFIG=SUPABASE_CONFIG;console.log('📦 Supabase configuration loaded');if(window.supabase){initializeSupabase()}
